paths:
    migrations: %%PHINX_CONFIG_DIR%%/../migrations
    seeds: %%PHINX_CONFIG_DIR%%/../seeds

environments:
    development:
        adapter: mysql
        host: localhost
        name: development_db
        user: root
        pass: ''
        port: 3306
        charset: utf8
